In [14]:
import sys
sys.path.append('../')
from library.finite_difference import *
import numpy as np

In [15]:
f = lambda x: np.exp(x) 
solve_d = upp_sovler_d()

solve_d.set_interval(0,1,1000)

start = ('dirichlet', 1.)
end = ('dirichlet', np.exp(1))
solve_d.set_boundary(start, end)

solve_d.set_f(f)

x, y = solve_d.solve()

solve_d.set_interval(0,1,1000)
solve_d.set_boundary(('dirichlet', 3.),('dirichlet', 3.*np.exp(1)))
solve_d.set_f(lambda t: 3*np.exp(t))

x2, y2 = solve_d.solve()




[[       0.  1000000.  1000000. ...  1000000.  1000000.  1000000.]
 [-2000000. -2000000. -2000000. ... -2000000. -2000000. -2000000.]
 [ 1000000.  1000000.  1000000. ...  1000000.  1000000.        0.]]
[0. 0. 0. ... 0. 0. 0.]
[0.    0.001 0.002 ... 0.998 0.999 1.   ]
[[       0.  1000000.  1000000. ...  1000000.  1000000.  1000000.]
 [-2000000. -2000000. -2000000. ... -2000000. -2000000. -2000000.]
 [ 1000000.  1000000.  1000000. ...  1000000.  1000000.        0.]]
[0. 0. 0. ... 0. 0. 0.]
[0.    0.001 0.002 ... 0.998 0.999 1.   ]


In [16]:
e = y - 1.*np.exp(x)
print(np.linalg.norm(e, ord=np.inf))

e2 = y2 - 3*np.exp(x2)
print(e2)
print(np.linalg.norm(e2, ord=np.inf))

1.765609525250511e-08
[0.00000000e+00 1.79449344e-10 3.58648222e-10 ... 4.98662445e-10
 2.49670506e-10 0.00000000e+00]
5.296826888212536e-08
